Algoritmo "Laço de repetição para(for)
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Exemplo do laço de repetição para(for)
// Autor(a)    : Alan
// Data atual  : 18/09/2023
Var
   // Seção de Declarações das variáveis
   contadora : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de  1  ate 100 passo 1 faca
      Escreval(contadora)
   fimpara

Fimalgoritmo